### ISSUE TITLE
[Research] Generate additional sources and sinks: Go

### ISSUE THREAD

**Issue by inkz** [returntocorp/sgrep-rules#1495]
- [ ] create a list of possible sources for Go web frameworks
- [ ] create rule(s) for identifying possible sinks
- [ ] generate extensive list of repositories (~1000 repos) that are applicable for the research (Go lang, use web frameworks)
- [ ] run rule(s) on the generated inputset
- [ ] wrap found sinks into a Google sheet

**Comment by minusworld** [comment]
I've generated some sources/sinks using the following sources:
- `r.URL.Query(...)`
- `r.FormFile(...)`

Will add them to the spreadsheet soon

**Comment by minusworld** [comment]
I just added a bunch of sources/sinks for Go to the spreadsheet. 

https://docs.google.com/spreadsheets/d/1k-VGANT6q-zbQVmvkLFpXvUiATyYzIA0xUbNPA_BwXo/edit#gid=1724411655

I used this rule which should grab anything that a Request object touches to generate a bunch of data. (https://semgrep.dev/s/xqj0)

```yaml
rules:
  - id: httprequest-sinks-go
    languages:
      - go
    message: $SINK
    mode: taint
    pattern-sinks:
      - pattern: $SINK(...)
    pattern-sources:
      - pattern-either:
          - pattern: "($REQUEST : *http.Request).$ANYTHING"
          - pattern: "($REQUEST : http.Request).$ANYTHING"
    severity: INFO
```

Some interesting touch points for further investigation :male-detective::skin-tone-3:

- `err = yaml.Unmarshal([]byte(tokenStr), token)`
- `w.Header().Add("Location", newURL)`
- `io.WriteString(w, "Hitting "+os.Args[1]+" with "+r.URL.Path+"\n")`
