### ISSUE TITLE
Filter constant values from `dangerouslySetInnerHTML`

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-rules#1639]
**Describe the bug**
The dangerouslySetInnerHTML rule is currently noisy due to lack of constant filtering. @chgg-kboberg gave us this sample: https://semgrep.dev/s/chgg-kboberg:context_aware_dangerouslysetinnerhtml as a potential alternative. However, it uses a top-of-pattern ellipsis and may be able to be optimized.

Let's see if we can do a good job filtering out constants and push an updated version of this rule.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [x] P2: annoying but not blocking me

**Comment by kurt-r2c** [comment]
FWIW, it looks like I improved this rule before leaving and it no longer has a leading ellipsis:

```yaml
rules:
  - id: react-dangerouslysetinnerhtml
    patterns:
      - pattern-either:
          - pattern: |
              <$X dangerouslySetInnerHTML={$INNER_SET} />
          - pattern: |
              {dangerouslySetInnerHTML: $INNER_SET}
      - pattern-inside: |
          const $CONST = "...";
          ...
      - metavariable-pattern:
          metavariable: $INNER_SET
          patterns:
            - pattern-not: |
                { __html: "..." }
            - pattern-not: |
                { __html: $CONST }
    message: >
      Setting HTML from code is risky because it’s easy to inadvertently expose
      your users to a cross-site scripting (XSS) attack.  Semgrep cannot prove
      $INNER_SET is safe.
    languages:
      - js
    severity: WARNING
    metadata:
      cwe: "CWE-79: Improper Neutralization of Input During Web Page Generation
        ('Cross-site Scripting')"
      owasp: "A7: Cross-Site Scripting (XSS)"
      references:
        - https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml
      category: security
      technology:
        - react
      license: Commons Clause License Condition v1.0[LGPL-2.1-only]
```
