### ISSUE TITLE
[Rule] PHP taint mode cross-site scripting (XSS) echoing user input

### ISSUE THREAD

**Issue by Sjord** [returntocorp/sgrep-rules#2369]
**Rule Description**

Cross-site scripting, specifically HTML injection.

**Examples or references**

```
<?php
echo "Hello ".$_GET["name"];
```

**Additional information**

Something like this:

```
rules:
- id: user-input-is-echoed
  mode: taint
  message: XSS
  languages: [php]
  severity: ERROR
  pattern-sources:
  - pattern: $_REQUEST[...]
  - pattern: $_GET[...]
  - pattern: $_POST[...]
  pattern-sinks:
  - pattern: echo ...;
  pattern-sanitizers:
  - pattern: htmlentities(...)
  - pattern: htmlspecialchars(...)
  metadata:
    cwe: "CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
    owasp: 
    - "A03:2021 - Injection"
    - "A07:2017 - Cross-Site Scripting (XSS)"
    category: security
```

**PR Checklist**
- [ ] This ticket has links, references, or examples.
- [ ] The rule has **true positive** and **true negative** test cases in a file that matches the rule name.

> If the rule is `my-rule`, the test file name should be `my-rule.js`.
>
> True positives are marked by comments with `ruleid: <my-rule>` and true negatives are marked by comments with `ok: <my-rule>`.

- [ ] The rule has a good message. A good message includes:

> 1. A description of the pattern (e.g., missing parameter, dangerous flag, out-of-order function calls).
> 1. A description of why this pattern was detected (e.g., logic bug, introduces a security vulnerability, bad practice).
> 1. An alternative that resolves the issue (e.g., use another function, validate data first, discard the dangerous flag).

- [ ] After the PR has been reviewed and approved, merge the rule and close this ticket! Thanks for contributing!
