### ISSUE TITLE
Confusing description in detect-non-literal-fs-filename

### ISSUE THREAD

**Issue by Sjord** [returntocorp/sgrep-rules#2424]
https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/lang/security/audit/detect-non-literal-fs-filename.yaml

> Detected function `$ARG` enter fs module.

Should this be "parameter" instead of "function"?

**Comment by LewisArdern** [comment]
I think because it originates from a function argument it's okay?
```
  pattern-sources:
  - patterns:
    - pattern-inside: function ... (..., $ARG,...) {...}
    - focus-metavariable: $ARG
 ```
