### ISSUE TITLE
[javascript] match inside function second argument

### ISSUE THREAD

**Issue by jonny64** [returntocorp/sgrep-rules#2476]
**Is your feature request related to a problem? Please describe.**
```
let filter = {key: USER_INPUT}
let data = {... ...}
add_vocabularies (data, {voc_some: {filter}, voc_other: {}, voc_etc: {}})
```
how do I match USER_INPUT in second argument?

**Describe alternatives you've considered**
this gives false positive even if USER_INPUT goes to data (which is OK)
```
    languages:
      - js
    message: this.rq.$X injected in db.add_vocabularies without sanitizing!
    mode: taint
    pattern-sources:
      - pattern: USER_INPUT
    pattern-sinks:
      - pattern: add_vocabularies($DATA, <... {..., filter:$X, ...} ...>)
```

**Use case**
integrating semgrep in workflow, finding meaningful results

**Describe the solution you'd like**
no false positive, match inside function second argument

** Some more **
another question, how do I match this.db when an alias was created
```
const db = this.db
db.add_vocabularies (...)
```
