### ISSUE TITLE
s3-unencrypted-bucket.tf is outdated

### ISSUE THREAD

**Issue by hikarunoryoma** [returntocorp/sgrep-rules#2811]
**Describe the bug**
According to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket the argument for encrypting buckets is deprecated in `aws_s3_bucket` argument.  Instead the `aws_s3_bucket_server_side_encryption_configuration` resource should be used.  This check should check that if there is an aws_s3_bucket that there is a server_side_encryption configured.  

Another thing you could do is not apply this rule anymore since on Jan 5, 2023 all buckets are by default encrypted.  https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-encryption.html.  

**To Reproduce**
Have a terraform file with the following resources: 
```
resource "aws_s3_bucket" "bucket" {
  bucket = "bucketName"
}

resource "aws_s3_bucket_server_side_encryption_configuration" "bucket" {
  bucket = aws_s3_bucket.env_bucket.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "aws:kms"
    }
  }
}
```

**Expected behavior**
No longer flag aws_s3_bucket resources that do not have an encryption.

**Priority**
How important is this to you?
- [X ] P2: annoying but not blocking me

**Reproduced via github actions with the following yml settings: 
```
name: Terraform Vulnerability Scan

on:
  push:
    branches: [main]
    paths:
      - "terraform/**"
  pull_request:
    branches: [main]
    paths:
      - "terraform/**"

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      # Fetch project source with GitHub Actions Checkout.
      - uses: actions/checkout@v3

      - run: semgrep ci
        env:
          SEMGREP_RULES: p/terraform
```
