### ISSUE TITLE
Enhance Python eval() detection rule

### ISSUE THREAD

**Issue by user1-v0** [returntocorp/sgrep-rules#2999]
**Describe the bug**
The current rule needs some improvements in detecting `eval()` especially if it accepts _f-string_ (`f" some string "`) as an argument. 

**To Reproduce**
Rule can't properly detect `eval()` in the following code snippets:
```python3
def eval_something(something):
    # ruleid:eval-detected
    eval(f"some_func({{something}})")
```
```python3
user_input = "command injection payload"
# ruleid:eval-detected
eval(f"some_func({user_input})")
```
```python3
# ok:eval-detected
eval("")

# ok:eval-detected
eval(f"")
```
**Expected behavior**
The rule should detect all `eval()` calls that don't have an empty string, static string, and _f-string_ without `{}` as an argument. The detection can be done by updating the pattern to use metavariable and RegEx. In this way, we can reduce the number of false positives by ignoring all `eval()` calls that don't rely on external sources.

```yaml
- pattern: eval($ARG)
    - metavariable-pattern:
        metavariable: $ARG
        patterns:
          - pattern-not-regex: (^f")([^{}]*)("$)
          - pattern-not-regex: (^")(.*)("$)
```
 Please review my pull request #2997. Thanks

**Priority**
- [ ] P0: blocking me from making progress
- [ ] P1: this will block shortlyure
- [x] P2: annoying but not blocking me
